defaults:
  - dataset: ABIDE
  - model: lrbgt # brainnetcnn, fbnetgen, lrbgt, transformer
  - optimizer: adam
  - training: basic_training
  - datasz: 100p
  - preprocess: mixup

repeat_time: 10
log_path: result
save_learnable_graph: False

# wandb
wandb_entity: eggroup
project: brainnetworktransformer
